//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        public int LoanId { get; set; }
        public string PropertyLocation { get; set; }
        public string PropertyName { get; set; }
        public decimal EstimatedCostOfProperty { get; set; }
        public decimal AmountRequired { get; set; }
        public decimal MonthlyIncome { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public decimal AadharNumber { get; set; }
        public string PanNumber { get; set; }
        public bool Verified { get; set; }
        public bool Approved { get; set; }
    }
}
