//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UserRegistration
    {
        public int UserId { get; set; }

        [Required(ErrorMessage = "This Field is Required.")]
        public string Name { get; set; }



        [Required(ErrorMessage = "This Field is Required.")]
        public string MailAddress { get; set; }



        [Required]
        public int ContactNumber { get; set; }


        [Required(ErrorMessage ="This Field is Required.")]
        public string UserName { get; set; }



        [Required(ErrorMessage = "This Field is Required.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }


        [DataType(DataType.Password)]
        [DisplayName("Confirm Password")]
        [Compare("Password")]
        [Required(ErrorMessage = "This Field is Required.")]
        public string ConfirmPassword { get; set; }
    }
}
